source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout")
]

source/api_v1/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import QuoteViewSet, get_token_view

router = DefaultRouter()
router.register('quote', QuoteViewSet, basename='quote')


app_name = 'api'


urlpatterns = [
    path('', include(router.urls)),
    path('get-csrf-token/', get_token_view, name='get_token'),
]

source/hello/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api_v1.urls'))
]

source/webapp/urls.py
from django.urls import path

from webapp.views import index_view

app_name = 'webapp'


urlpatterns = [
    path('', index_view, name='index'),
]

source/accounts/models.py
from django.db import models

# Create your models here.

source/api_v1/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.db import models

CATEGORY_CHOICES = [('new', 'Новая'),
                    ('moderated', 'Промодерированная')]


class Quote(models.Model):
    text = models.TextField(max_length=2000, verbose_name='Текст')
    author = models.CharField(max_length=100, verbose_name='Автор')
    email = models.EmailField(verbose_name='Email')
    rating = models.IntegerField(default=0, verbose_name='Рейтинг')
    status = models.CharField(max_length=17, choices=CATEGORY_CHOICES, default='new', verbose_name="Статус")
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    @classmethod
    def get_moderated(cls):
        return cls.objects.filter(status='moderated')

    def __str__(self):
        return f'{self.text}'

    class Meta:
        verbose_name = 'Цитата'
        verbose_name_plural = 'Цитаты'


class Vote(models.Model):
    session_key = models.CharField(max_length=40, verbose_name='Ключ сессии')
    quote = models.ForeignKey(Quote, related_name='votes', on_delete=models.CASCADE,
                              verbose_name='Цитата')
    rating = models.IntegerField(choices=((1, 'up'), (-1, 'down')), verbose_name='Рейтинг')

    def __str__(self):
        return f'{self.rating} {self.quote}'

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'
        ordering = ('quote', 'rating')

source/accounts/views.py
from django.shortcuts import render

# Create your views here.

source/api_v1/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import ensure_csrf_cookie
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet, ViewSet
from api_v1.serializers import QuoteCreateSerializer, QuoteUpdateSerializer, QuoteSerializer
from webapp.models import Quote, Vote
from django.contrib.sessions.models import Session


@ensure_csrf_cookie
def get_token_view(request, *args, **kwargs):
    if request.method == 'GET':
        return HttpResponse()
    return HttpResponseNotAllowed('Only GET request are allowed')


class QuoteViewSet(ModelViewSet):

    def get_queryset(self):
        if self.request.method == 'GET' and \
                not self.request.user.has_perm('webapp.quote_view'):
            return Quote.get_moderated()
        return Quote.objects.all()

    def get_serializer_class(self):
        if self.request.method == 'POST':
            return QuoteCreateSerializer
        elif self.request.method == 'PUT':
            return QuoteUpdateSerializer
        return QuoteSerializer

    @action(methods=['post'], detail=True)
    def Up(self, request, pk=None):
        if not self.request.session.session_key:
            self.request.session.save()
        session = Session.objects.get(session_key=self.request.session.session_key)
        quote = get_object_or_404(Quote, pk=pk)
        try:
            print(session.session_key)
            vote = Vote.objects.get(quote_id=quote.pk, session_key=session.session_key)
        except ObjectDoesNotExist:
            print(quote.status)
            vote = Vote.objects.create(rating=1, quote_id=quote.pk, session_key=session.session_key)
            quote.rating += 1
            quote.save()
        return Response({'rating': quote.rating})

    @action(methods=['post'], detail=True)
    def Down(self, request, pk=None):
        if not self.request.session.session_key:
            self.request.session.save()
        session = Session.objects.get(session_key=self.request.session.session_key)
        quote = get_object_or_404(Quote, pk=pk)
        try:
            vote = Vote.objects.get(quote_id=quote.pk, session_key=session.session_key)
        except ObjectDoesNotExist:
            print(quote.status)
            vote = Vote.objects.create(rating=-1, quote_id=quote.pk, session_key=session.session_key)
            quote.rating -= 1
            quote.save()
        return Response({'rating': quote.rating})

source/webapp/views.py
from django.shortcuts import render


def index_view(request, *args, **kwargs):
    return render(request, 'base.html')

source/accounts/templates/login.html
{% extends 'base.html' %}
{% block title %}Вход{% endblock %}
{% block content %}
    <h1>Вход</h1>
    <form method="post" class="text-center ms-auto me-auto w-50">
        {% csrf_token %}
        {% if form.has_error %}
            <p class="text-danger">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="container w-50">
            <div class="form-group">
                <label for="username" class="form-label">Имя пользователя:</label>
                <input type="text" name="username" id="username" class="form-control">
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Пароль:</label>
                <input type="password" name="password" id="password" class="form-control">
            </div>
        </div>
        <button class="mt-3 btn btn-primary" type="submit">Войти</button>
    </form>
{% endblock %}

source/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}Document{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body>
<nav class="navbar navbar-expand-lg text-light fs-5">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ">
                {% block nav %}
                    <div class="menu mt-5 display-inline">
                        {% if not user.is_authenticated %}
                            <a id="onclick" class="btn btn-outline-primary fs-5"
                               href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Войти</a>
                        {% else %}
                            <a id="onclick" class="btn btn-outline-primary fs-5" aria-current="page"
                               href="{% url 'accounts:logout' %}">{{ user.username }} | Выйти</a>
                        {% endif %}
                        <a id="main" class="btn btn-outline-primary fs-5"
                           href="#">Главная</a>
                        <a id="addQuote" class="btn btn-outline-primary fs-5" href="#">Добавить
                            цитату</a>
                    </div>
                {% endblock %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="box" id="get" style="display: none;"></div>
    <div class="box" id="post" style="display: none;">
        <form action="">
            <div class="box">
                <div class="mb-3 w-50">
                    <textarea class="input" placeholder="Цитата" id="text"></textarea>
                </div>
                <div class="mb-3 w-50">
                    <input class="input" type="text" id="author" placeholder="Автор">
                </div>
                <div class="mb-3 w-50">
                    <input class="input" type="email" id="email" placeholder="Email">
                </div>
                <input class="input" id="submit" type="submit">
            </div>
        </form>
    </div>

    <div class="box" id="put" style="display: none;">
        <form id="update_form" action="">
            <div class="box">
                <div class="mb-3 w-50">
                    <textarea class="input" placeholder="Цитата" id="text_update"></textarea>
                </div>
                <div class="mb-3 w-50">
                    <input class="input" type="text" id="status_update" placeholder="Статус">
                </div>
                <input class="input" id="submit" type="update_submit">
            </div>
        </form>
    </div>

    <div id="message" class="box" style="display: none;">
    </div>
    <div id="Quote" class="box" style="display: none;">
    </div>

    {% block content %}{% endblock %}
</div>
<script src="{% static "js/main.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>